/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  shapeCategory,
} from './components/parts-first/parts-first';

export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface EachProduct {
    'productURL': string;
  }
  interface ListOfRoutes {}
  interface PartsFirst {
    'categoryName': shapeCategory;
    'fifthProp': shapeCategory;
    'firstProp': shapeCategory;
    'fourthProp': shapeCategory;
    'nonExistant': string;
    'secondProp': shapeCategory;
    'sixthProp': shapeCategory;
    'thirdProp': shapeCategory;
  }
  interface ProductCards {
    'category': "string";
  }
  interface SideNav {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEachProductElement extends Components.EachProduct, HTMLStencilElement {}
  var HTMLEachProductElement: {
    prototype: HTMLEachProductElement;
    new (): HTMLEachProductElement;
  };

  interface HTMLListOfRoutesElement extends Components.ListOfRoutes, HTMLStencilElement {}
  var HTMLListOfRoutesElement: {
    prototype: HTMLListOfRoutesElement;
    new (): HTMLListOfRoutesElement;
  };

  interface HTMLPartsFirstElement extends Components.PartsFirst, HTMLStencilElement {}
  var HTMLPartsFirstElement: {
    prototype: HTMLPartsFirstElement;
    new (): HTMLPartsFirstElement;
  };

  interface HTMLProductCardsElement extends Components.ProductCards, HTMLStencilElement {}
  var HTMLProductCardsElement: {
    prototype: HTMLProductCardsElement;
    new (): HTMLProductCardsElement;
  };

  interface HTMLSideNavElement extends Components.SideNav, HTMLStencilElement {}
  var HTMLSideNavElement: {
    prototype: HTMLSideNavElement;
    new (): HTMLSideNavElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'each-product': HTMLEachProductElement;
    'list-of-routes': HTMLListOfRoutesElement;
    'parts-first': HTMLPartsFirstElement;
    'product-cards': HTMLProductCardsElement;
    'side-nav': HTMLSideNavElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface EachProduct extends JSXBase.HTMLAttributes<HTMLEachProductElement> {
    'productURL'?: string;
  }
  interface ListOfRoutes extends JSXBase.HTMLAttributes<HTMLListOfRoutesElement> {}
  interface PartsFirst extends JSXBase.HTMLAttributes<HTMLPartsFirstElement> {
    'categoryName'?: shapeCategory;
    'fifthProp'?: shapeCategory;
    'firstProp'?: shapeCategory;
    'fourthProp'?: shapeCategory;
    'nonExistant'?: string;
    'secondProp'?: shapeCategory;
    'sixthProp'?: shapeCategory;
    'thirdProp'?: shapeCategory;
  }
  interface ProductCards extends JSXBase.HTMLAttributes<HTMLProductCardsElement> {
    'category'?: "string";
  }
  interface SideNav extends JSXBase.HTMLAttributes<HTMLSideNavElement> {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'each-product': EachProduct;
    'list-of-routes': ListOfRoutes;
    'parts-first': PartsFirst;
    'product-cards': ProductCards;
    'side-nav': SideNav;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


